### ISSUE TITLE
csv-to-csvw improvements

### ISSUE THREAD

**Issue by roblinksdata** [GDonRanasinghe/csv-to-csvw#1]
This is a placholder issue to hold the improvements we want to make to the csv-to-csvw github workflow:

- [x] Ensure that when a CSV gets deleted from the repository, the CSV-W also gets deleted from the out folder + gh-pages branch.
- [x] Ensure we're looking for `.json` files instead of the non-standard `.csv.json` (@GDonRanasinghe to check)
- [x] make sure that any validation-errors.json files are picked up and archived as artifacts
- [x] When updating a CSV file's content, the inspect command output txt file is **appended to** when it should be wiped and **replaced** each time.
- [x] Run the inspect command on code-list outputs as well as cubes which are built.
- [x] Can we remove the need for the csv folder? It'd be better if we could pick up any CSV/JSON file pairs throughout the repository.
- [x] Order outputs alphabetically in the index.html output.

- [x] Create a new ticket to implement this workflow as a github action so a user can write their own workflow and don't have to fork the repo - formally publishing to github.

**Comment by GDonRanasinghe** [comment]
@robons You are correct on the `.json` vs `.csv.json` - I will update accordingly.

**Comment by GDonRanasinghe** [comment]
The new ticket for publishing the csv-to-csvw workflow is at: https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gss-cogs/csv-to-csvw/2
